# Pull the 'openthinker:7b' model from Ollama
ollama pull deepseek-coder:6.7b
ollama pull deepseek-coder-v2:16b
ollama pull llama3.2-vision:11b
ollama pull openthinker:7b
ollama pull qwen2.5-coder:7b
ollama pull qwen2.5-coder:14b
ollama pull codellama:7b
ollama pull codellama:13b
ollama pull starcoder2:7b
ollama pull starcoder2:15b
ollama pull mistral-nemo:12b
ollama pull dolphin3:8b
ollama pull llama3.2-vision:11b
ollama pull llama2-uncensored:7b
ollama pull llama2:13b
ollama pull llama2:7b
ollama pull qwen2.5:7b
ollama pull qwen2.5:14b
ollama pull codegemma:7b
ollama pull codellama:7b
ollama pull codellama:13b
ollama pull mistral:7b
ollama pull dolphin-llama3:8b
ollama pull llama3.1:8b
ollama pull llama3.2:3b
#Supports image input
ollama pull llava:7b
ollama pull llava:13b
